### ISSUE TITLE
Pip install not working

### ISSUE THREAD

**Issue by davidenoma** [fastlmm/PySnpTools#7]
```
          from cffi._shimmed_dist_utils import Extension
        File "/private/var/folders/6j/fd352vhx3g5fq39r4xj_n50r0000gn/T/pip-build-env-hws2l1ni/overlay/lib/python3.12/site-packages/cffi/_shimmed_dist_utils.py", line 16, in <module>
          raise Exception("This CFFI feature requires setuptools on Python >= 3.12. The setuptools module is missing or non-functional.") from ex
      Exception: This CFFI feature requires setuptools on Python >= 3.12. The setuptools module is missing or non-functional.
      Traceback (most recent call last):
        File "/opt/homebrew/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/homebrew/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/6j/fd352vhx3g5fq39r4xj_n50r0000gn/T/pip-build-env-hws2l1ni/overlay/lib/python3.12/site-packages/poetry/core/masonry/api.py", line 58, in build_wheel
          return WheelBuilder.make_in(
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/6j/fd352vhx3g5fq39r4xj_n50r0000gn/T/pip-build-env-hws2l1ni/overlay/lib/python3.12/site-packages/poetry/core/masonry/builders/wheel.py", line 88, in make_in
          wb.build(target_dir=directory)
        File "/private/var/folders/6j/fd352vhx3g5fq39r4xj_n50r0000gn/T/pip-build-env-hws2l1ni/overlay/lib/python3.12/site-packages/poetry/core/masonry/builders/wheel.py", line 123, in build
          self._build(zip_file)
        File "/private/var/folders/6j/fd352vhx3g5fq39r4xj_n50r0000gn/T/pip-build-env-hws2l1ni/overlay/lib/python3.12/site-packages/poetry/core/masonry/builders/wheel.py", line 172, in _build
          self._run_build_script(self._package.build_script)
        File "/private/var/folders/6j/fd352vhx3g5fq39r4xj_n50r0000gn/T/pip-build-env-hws2l1ni/overlay/lib/python3.12/site-packages/poetry/core/masonry/builders/wheel.py", line 262, in _run_build_script
          subprocess.check_call([self.executable.as_posix(), build_script])
        File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/opt/homebrew/Cellar/python@3.12/3.12.3/bin/python3.12', 'build_ext.py']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cbgen
Failed to build cbgen
ERROR: Could not build wheels for cbgen, which is required to install pyproject.toml-based projects

```

I try on bash and still 
davidenoma$ pip install pysnptools
Requirement already satisfied: pysnptools in /opt/homebrew/lib/python3.11/site-packages (0.5.11)
Requirement already satisfied: scipy>=1.1.0 in /opt/homebrew/lib/python3.11/site-packages (from pysnptools) (1.10.1)
Requirement already satisfied: numpy>=1.17.0 in /opt/homebrew/lib/python3.11/site-packages (from pysnptools) (1.23.5)
Requirement already satisfied: pandas>=1.1.1 in /opt/homebrew/lib/python3.11/site-packages (from pysnptools) (2.0.2)
Requirement already satisfied: psutil>=5.6.3 in /opt/homebrew/lib/python3.11/site-packages (from pysnptools) (5.9.5)
Requirement already satisfied: h5py>=2.10.0 in /opt/homebrew/lib/python3.11/site-packages (from pysnptools) (3.8.0)
Requirement already satisfied: cloudpickle>=2.2.0 in /opt/homebrew/lib/python3.11/site-packages (from pysnptools) (3.0.0)
Requirement already satisfied: more-itertools>=8.7.0 in /opt/homebrew/lib/python3.11/site-packages (from pysnptools) (10.2.0)
Requirement already satisfied: cbgen>=1.0.4 in /opt/homebrew/lib/python3.11/site-packages (from pysnptools) (1.0.4)
Requirement already satisfied: bgen-reader>=4.0.8 in /opt/homebrew/lib/python3.11/site-packages (from pysnptools) (4.0.8)
Requirement already satisfied: bed-reader>=1.0.0 in /opt/homebrew/lib/python3.11/site-packages (from pysnptools) (1.0.4)
Requirement already satisfied: appdirs>=1.4.3 in /opt/homebrew/lib/python3.11/site-packages (from bgen-reader>=4.0.8->pysnptools) (1.4.4)
Requirement already satisfied: cachetools>=3.1.1 in /opt/homebrew/lib/python3.11/site-packages (from bgen-reader>=4.0.8->pysnptools) (5.3.1)
Requirement already satisfied: dask>=2.12.0 in /opt/homebrew/lib/python3.11/site-packages (from dask[array,bag,dataframe,delayed]>=2.12.0->bgen-reader>=4.0.8->pysnptools) (2024.5.1)
Requirement already satisfied: pytest>=5.4.1 in /opt/homebrew/lib/python3.11/site-packages (from bgen-reader>=4.0.8->pysnptools) (8.2.1)
Requirement already satisfied: requests>=1.25.8 in /opt/homebrew/lib/python3.11/site-packages (from bgen-reader>=4.0.8->pysnptools) (2.31.0)
Requirement already satisfied: texttable>=1.6.2 in /opt/homebrew/lib/python3.11/site-packages (from bgen-reader>=4.0.8->pysnptools) (1.7.0)
Requirement already satisfied: tqdm>=4.43.0 in /opt/homebrew/lib/python3.11/site-packages (from bgen-reader>=4.0.8->pysnptools) (4.65.0)
Requirement already satisfied: xarray>=0.16.0 in /opt/homebrew/lib/python3.11/site-packages (from bgen-reader>=4.0.8->pysnptools) (2024.5.0)
Requirement already satisfied: cffi in /opt/homebrew/lib/python3.11/site-packages (from cbgen>=1.0.4->pysnptools) (1.15.1)
Requirement already satisfied: pooch in /opt/homebrew/lib/python3.11/site-packages (from cbgen>=1.0.4->pysnptools) (1.8.1)
Requirement already satisfied: urllib3>=1.26 in /opt/homebrew/lib/python3.11/site-packages (from cbgen>=1.0.4->pysnptools) (1.26.16)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/homebrew/lib/python3.11/site-packages (from pandas>=1.1.1->pysnptools) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/homebrew/lib/python3.11/site-packages (from pandas>=1.1.1->pysnptools) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /opt/homebrew/lib/python3.11/site-packages (from pandas>=1.1.1->pysnptools) (2023.3)
Requirement already satisfied: click>=8.1 in /opt/homebrew/lib/python3.11/site-packages (from dask>=2.12.0->dask[array,bag,dataframe,delayed]>=2.12.0->bgen-reader>=4.0.8->pysnptools) (8.1.3)
Requirement already satisfied: fsspec>=2021.09.0 in /opt/homebrew/lib/python3.11/site-packages (from dask>=2.12.0->dask[array,bag,dataframe,delayed]>=2.12.0->bgen-reader>=4.0.8->pysnptools) (2023.12.1)
Requirement already satisfied: packaging>=20.0 in /opt/homebrew/lib/python3.11/site-packages (from dask>=2.12.0->dask[array,bag,dataframe,delayed]>=2.12.0->bgen-reader>=4.0.8->pysnptools) (23.1)
Requirement already satisfied: partd>=1.2.0 in /opt/homebrew/lib/python3.11/site-packages (from dask>=2.12.0->dask[array,bag,dataframe,delayed]>=2.12.0->bgen-reader>=4.0.8->pysnptools) (1.4.2)
Requirement already satisfied: pyyaml>=5.3.1 in /opt/homebrew/lib/python3.11/site-packages (from dask>=2.12.0->dask[array,bag,dataframe,delayed]>=2.12.0->bgen-reader>=4.0.8->pysnptools) (6.0)
Requirement already satisfied: toolz>=0.10.0 in /opt/homebrew/lib/python3.11/site-packages (from dask>=2.12.0->dask[array,bag,dataframe,delayed]>=2.12.0->bgen-reader>=4.0.8->pysnptools) (0.12.1)
Requirement already satisfied: importlib-metadata>=4.13.0 in /opt/homebrew/lib/python3.11/site-packages (from dask>=2.12.0->dask[array,bag,dataframe,delayed]>=2.12.0->bgen-reader>=4.0.8->pysnptools) (7.0.0)
Requirement already satisfied: dask-expr<1.2,>=1.1 in /opt/homebrew/lib/python3.11/site-packages (from dask[array,bag,dataframe,delayed]>=2.12.0->bgen-reader>=4.0.8->pysnptools) (1.1.1)
Requirement already satisfied: iniconfig in /opt/homebrew/lib/python3.11/site-packages (from pytest>=5.4.1->bgen-reader>=4.0.8->pysnptools) (2.0.0)
Requirement already satisfied: pluggy<2.0,>=1.5 in /opt/homebrew/lib/python3.11/site-packages (from pytest>=5.4.1->bgen-reader>=4.0.8->pysnptools) (1.5.0)
Requirement already satisfied: six>=1.5 in /opt/homebrew/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas>=1.1.1->pysnptools) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/homebrew/lib/python3.11/site-packages (from requests>=1.25.8->bgen-reader>=4.0.8->pysnptools) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /opt/homebrew/lib/python3.11/site-packages (from requests>=1.25.8->bgen-reader>=4.0.8->pysnptools) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /opt/homebrew/lib/python3.11/site-packages (from requests>=1.25.8->bgen-reader>=4.0.8->pysnptools) (2023.5.7)
Requirement already satisfied: pycparser in /opt/homebrew/lib/python3.11/site-packages (from cffi->cbgen>=1.0.4->pysnptools) (2.21)
Requirement already satisfied: platformdirs>=2.5.0 in ./Library/Python/3.11/lib/python/site-packages (from pooch->cbgen>=1.0.4->pysnptools) (4.1.0)
Requirement already satisfied: pyarrow>=7.0.0 in /opt/homebrew/lib/python3.11/site-packages (from dask-expr<1.2,>=1.1->dask[array,bag,dataframe,delayed]>=2.12.0->bgen-reader>=4.0.8->pysnptools) (14.0.1)
Requirement already satisfied: zipp>=0.5 in /opt/homebrew/lib/python3.11/site-packages (from importlib-metadata>=4.13.0->dask>=2.12.0->dask[array,bag,dataframe,delayed]>=2.12.0->bgen-reader>=4.0.8->pysnptools) (3.17.0)
Requirement already satisfied: locket in /opt/homebrew/lib/python3.11/site-packages (from partd>=1.2.0->dask>=2.12.0->dask[array,bag,dataframe,delayed]>=2.12.0->bgen-reader>=4.0.8->pysnptools) (1.0.0)
(base) Davids-MacBook-Air:~ davidenoma$ python
Python 3.11.9 (main, Apr 19 2024, 11:43:47) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysnptools
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pysnptools'
>>>

**Comment by CarlKCarlK** [comment]
Greetings! Thanks using (or trying to use) PySnpTools.

The issue is likely `cbgen` [issue #14](https://github.com/limix/cbgen/issues/14).

Please try this:

```bash
pip uninstall bgen-reader
pip uninstall cbgen
pip install cbgen
```

I assume it will fail but let me know. If you don't need to read `*.bgen` files, I can likely make a workaround so that PySnpTools won't depend on `cbgen`.

-- Carl

Carl Kadie, Ph.D.
[FaST-LMM & PySnpTools Team](https://fastlmm.github.io/)
(Microsoft Research, retired)
https://www.linkedin.com/in/carlk/
Join the FaST-LMM user discussion and announcement list [via email](mailto:fastlmm-user-join@python.org?subject=Subscribe) (or use [web sign up](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmail.python.org%2Fmailman3%2Flists%2Ffastlmm-user.python.org&data=02%7C01%7C%7C13a5c33d7cd84cad5cdf08d7bba56e20%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637184191498409587&sdata=2CQWjQEwOpQol2rQ1eoyVTgY8WvInV8UH31Wtl68FzY%3D&reserved=0))

**Comment by CarlKCarlK** [comment]
Hi, (assuming you don't need to read BGEN format), please try a new beta version of PySnpTools:

`pip install pysnptools --pre --upgrade`

**Comment by davidenoma** [comment]
Hi Carl, I tried this approach 
pip install pysnptools --pre --upgrade 
and it works fine. 

I think it might have to do with the dependencies of bgen, particularly connecting homebrew, xcode, and python environments on MacOS. 

I tried using the pip install pysnptools on a new linux environment and it works perfectly. 

Thank you!
